name       : libcotp
version    : 1.2.2
release    : 1
source     :
    - https://github.com/paolostivanin/libcotp/archive/v1.2.2.tar.gz : 25b45ffa4aece5cc689503ebea7356a2f760c194f0c41805934495d2fe7165b1
license    : Apache-2.0
component  : programming.library
summary    : C library that generates TOTP and HOTP according to RFC-6238
description: |
    C library that generates TOTP and HOTP according to RFC-6238
builddeps  :
    - pkgconfig(baseencode)
    - pkgconfig(libgcrypt)
setup: |
    %cmake -DCMAKE_BUILD_TYPE=Release
build      : |
    %make
install    : |
    %make_install